# This file contains all default values supported by restic.
# You can omit any sections or values that are not relevant for your intended subcommand.
# Missing fields will be filled with defaults and validated automatically at runtime.

backup_log: /var/log/restic_full.log  # Log file for backup command
forget_log: /var/log/restic_forget.log  # Log file for forget command
snapshots_log: /var/log/restic_snapshots.log  # Log file for snapshots command
status_log: /var/log/restic_status.log  # Log file for status summary
stats_log: /var/log/restic_stats.log  # Log file for stats command

parent:
  # Repository access credentials and location
  repository: /mnt/restic/restic-beelink1
  repository_file: ""
  password_file: /etc/restic/.restic_password
  password_command: ""
  key_hint: ""
  tls_client_cert: ""
  cacert: ""

  # Caching & Performance
  cache_dir: ""
  cleanup_cache: false
  no_cache: false
  no_extra_verify: false
  no_lock: false
  retry_lock: ""
  limit_download: 0
  limit_upload: 0
  pack_size: 0
  compression: auto
  option: []

  # Security and behavior settings
  insecure_tls: false
  quiet: false
  json: false
  verbose: 0

snapshots:
  # Filter options
  host: []
  path: []
  tag: []

  # Display behavior
  compact: false
  group-by: ""
  latest: 0

forget:
  # Snapshot retention policies
  keep-last: 0
  keep-hourly: 0
  keep-daily: 14
  keep-weekly: 4
  keep-monthly: 6
  keep-yearly: 0

  # Time-based retention (relative to latest)
  keep-within: ""
  keep-within-hourly: ""
  keep-within-daily: ""
  keep-within-weekly: ""
  keep-within-monthly: ""
  keep-within-yearly: ""

  # Cleanup behavior
  prune: true
  dry-run: false
  group-by: ""
  host: []
  tag: []
  path: []

backup:
  # Data sources (what to back up)
  files-from: ""
  files-from-raw: ""
  files-from-verbatim: []
  stdin: ""
  stdin-filename: ""

  # Exclusions (what to skip)
  exclude:
    - /home/joerg/.cache
    - /home/joerg/.local/share/Trash
    - /home/joerg/.thumbnails
    - /home/joerg/.docker
    - /home/timeshift
    - /proc
    - /tmp
    - /timeshift
    - /sys
    - /run
    - /mnt
    - /media
    - /var/tmp
    - /var/cache
    - /swapfile
    - /var/lib/docker
  exclude-file: []
  exclude-if-present: []
  exclude-larger-than: ""
  exclude-caches: false
  iexclude: []
  iexclude-file: []

  # Backup behavior and scanning
  dry-run: false
  force: false
  ignore-ctime: false
  ignore-inode: false
  no-scan: false
  one-file-system: false
  with-atime: false
  read-concurrency: 0

  # Snapshot metadata and control
  host: ""
  tag: []
  group-by: ""
  parent: ""
  time: ""
  help: true

prune:
  max_unused: "5%"
  max_repack_size: ""
  repack_cacheable_only: false
  repack_small: false
  repack_uncompressed: false
  dry_run: false

check:
  read_data: false
  check_unused: false
  with_cache: true

diff:
  # Configuration options for the 'restic diff' command.
  # This command compares two snapshots to show file-level differences.
  from: "" # first snapshot ID
  to: "" # second snapshot ID
  metadata: false
  help: false

stats:
  # Statistics reporting configuration
  # Controls how restic computes and presents repository data summaries
  mode: restore-size
  host: []
  path: []
  tag: []
  snapshot_ids: [] # optional

init:
  # Configuration options for the 'restic init' command.
  # Used to initialize a new repository or copy parameters from another.
  copy_chunker_params: false
  from_repo: ""
  from_repository_file: ""
  from_password_file: ""
  from_password_command: ""
  from_key_hint: ""
  repository_version: "stable"

list:
  # List object type in the repository
  # Valid types are: blobs, packs, index, snapshots, keys, locks
  type: locks
